### PR TITLE
soapysdr: Add python build-dep

### PR DESCRIPTION
**Pull request by lool**
Fixes SoapySDR #119
https://github.com/pothosware/SoapySDR/issues/119

### CODE REVIEW

**Comment by guruofquality** [comment]
One worry was that osx also comes with python2, and that some people may want to use the osx version of python2 and not install the brew one. But I dont want to get a PR to remove this line because somebody wants to use the stock python. I have no idea if thats typical for brew python stuff though...

You kind of want it to be `depends_on "python" => :build` but only when python2 for brew is already installed. Do you happen to know how to check for existing installed packages in brew. Sorry for the over-complication...

**Comment by lool** [comment]
I hear what you're saying; I'm not sure how to do this properly. This:
http://docs.brew.sh/Homebrew-and-Python.html
suggests that both should be possible and that Brew defaults to the first python in PATH. In my case that's Brew's python, but clearly this combination was failing to build. I suspect it's combination of soapysdr's python-config detection and brew's python includes trimming that is unhappy, but I haven't found a similar python based formula we could derive from.

Perhaps it's enough to just have a python build option? Or perhaps we need to force PYTHONPATH from rb?

**Comment by lool** [comment]
Using the above ":recommended" is enough; I've found this in the vim recipe; could you confirm this is ok on brew systems without python?

**Comment by lool** [comment]
Oh hold on, did you want to also empower building against system python when the brew one is installed? That would also be possible, but I guess brew suggests this should be done by changing PATH?

**Comment by guruofquality** [comment]
> Oh hold on, did you want to also empower building against system python when the brew one is installed? That would also be possible, but I guess brew suggests this should be done by changing PATH?

Nah. I was just worried about changing existing behaviour, so if someone updates they wouldnt get brew python installed. If brew python is installed, and we build against brew python every time, that sounds good

**Comment by guruofquality** [comment]
http://docs.brew.sh/Python-for-Formula-Authors.html

> Python declarations
> Applications that are compatible with Python 2 should use the Apple-provided system Python in /usr/bin on systems that provide Python 2.7. To do this, declare:
> depends_on :python if MacOS.version <= :snow_leopard
> No explicit Python dependency is needed on recent OS versions since /usr/bin is always in PATH for Homebrew formulae; on Leopard and older, the python in PATH is used if it’s at least version 2.7, or else Homebrew’s python is installed.

**Comment by lool** [comment]
Tried with:
`depends_on :python if MacOS.version <= :snow_leopard`
but the build fails as before; I suspect it's with the python detection code in soapysdr, probably doesn't fly with brew's tricks

**Comment by guruofquality** [comment]
Well snow_leopard is fairly old, so that line effectively just means do not depend on python. So no real change, I was just pointing out that I think that the brew authors want us to not depend on python. We still have no idea what actually caused the error.

**Comment by guruofquality** [comment]
Alrighty then, not ideal, but better than broken. I will add recommends to pothospython as well, could have the same issue.

**Pull request merged**
